name: flutter_firebase_remote_config_demo
description: Flutter + Firebase Remote Config demo project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_remote_config: ^3.0.9
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.1
  flutter_riverpod: ^2.1.1
  flutter_slidable: ^2.0.0
  freezed_annotation: ^2.2.0
  go_router: ^5.2.2
  intl: ^0.17.0
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.2
  riverpod_annotation: ^1.0.6
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.0
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
